# DataSource Config
spring:
  elasticsearch:
    rest:
      uris: 124.70.137.86:9300
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://124.70.137.86:3306/eblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
  freemarker:
    settings:
      classic_compatible: true
      datetime_format: yyyy-MM-dd HH:mm
      number_format: 0.##
  redis:
    host: 124.70.137.86
    port: 6379
    password:
  rabbitmq:
    username: root
    password: password
    host: 124.70.137.86
    port: 5672
  thymeleaf:
    prefix: classpath:/templates/
    enabled: false